{% set name = "actinia-python-client" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/actinia-org/actinia-python-client/archive/{{ version }}.tar.gz
  sha256: 54cf1d7ffc20d8e61a4baa208eeb1dcfe852c8a6d3cc389fdb365a7b545c539e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.8
    - jinja2
    - requests
    - sphinx-material

test:
  imports:
    - actinia
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/actinia-org/actinia-python-client
  summary: Python Client Library for actinia
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anikaweinmann
    - neteler
    - giswqs
