{% set name = "actinia-python-client" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/actinia-org/actinia-python-client/archive/{{ version }}.tar.gz
  sha256: 2969f678e3257e9a773e4339d950accc290f3a64e0ac931d2368f054fdc7e0b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-git-versioning
    - pip
  run:
    - python >=3.8
    - jinja2
    - requests
    - sphinx-material

test:
  imports:
    - actinia
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/actinia-org/actinia-python-client
  summary: Python Client Library for actinia
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anikaweinmann
    - neteler
    - giswqs
